### ISSUE TITLE
derivatives of logs training problem 4

### ISSUE THREAD

**Issue by lewischl** [ofloveandhate/calculus_1#24]
the first two questions in this problem are missing a pair of parentheses in the 1 / ( ln a *x) in the code that returns the answer - i fixed it in mine!

**Comment by ofloveandhate** [comment]
thanks for catching this!  i fixed in mine, have not yet fixed in others'.  will close when i have propagated the fix.

**Comment by ofloveandhate** [comment]
fixed all over.
