### ISSUE TITLE
Derivatives power rule training, problems 1 and 2

### ISSUE THREAD

**Issue by weshuu** [ofloveandhate/calculus_1#36]
In problem 1, the video about e is the wrong video. The "name" of the video should be:

m2MIpDrF7Es

Also, at the start of problem 2, the "constant rule" is listed but the constant **multiple** rule is not.

**Comment by ofloveandhate** [comment]
problem 1 is fixed.  i also added a note about using prime notation for the sum and difference formulas.

problem 2, i added the constant multiple rule.

fixed for all instructors
