### ISSUE TITLE
derivatives of log functions - training

### ISSUE THREAD

**Issue by lewischl** [ofloveandhate/calculus_1#38]
problem 4 gives them a non-base e log to find the derivative of but when the base is chosen as 10, webwork renders it as log_1 0(x) rather than log_{10} (x)

**Comment by ofloveandhate** [comment]
thanks for finding this.  it's a stringification issue.  see https://webwork.maa.org/moodle/mod/forum/discuss.php?d=2961 for a bit on it.  basically, if a formula is written to string, should it be for machine use or human (tex) use?  if you want to see the solution to this problem, follow the commit url below once it's fixed.

**Comment by ofloveandhate** [comment]
I was wrong, this was just a curly brace issue, not a string-ification issue.

**Comment by ofloveandhate** [comment]
indeed, this is exactly what you said, i'm sorry.  i have done a lot of the texStrings / normalStrings thing lately and assumed it was that.
