### ISSUE TITLE
deriv applications extreme values problem 3

### ISSUE THREAD

**Issue by lewischl** [ofloveandhate/calculus_1#47]
not sure why but in the fifth drop down (another example) the correct derivative is (something)^{1/3} but entering 1/3 produces a "not enough valid points for comparison" error and the correct answer is given as (something)^{0.3333333333}. Since the problem had a 2/3 exponent, it would probably make sense to match style with a fractional power in the derivative.

**Comment by ofloveandhate** [comment]
I'll work on this one.  Thanks!

**Comment by ofloveandhate** [comment]
fixed in all instructors courses, and in the repo
