### ISSUE TITLE
integrals approximating area using rectangles - training: Problem 3

### ISSUE THREAD

**Issue by lewischl** [ofloveandhate/calculus_1#53]
In the step of approximating the total area, the left and right are mixed up. the current answer for L_3 is actually the right approximation and vice versa.

**Comment by ofloveandhate** [comment]
Did you already fix this in your webwork course, such that i can copy-paste a fix out of it, or do i need to cook up a fix?

**Comment by ofloveandhate** [comment]
ah, i see the fix, it's lines 164 and 165, need to swap the a and b.  i'll do it in a bit, i have to go teach.

**Comment by lewischl** [comment]
I fixed in mine!

**Comment by ofloveandhate** [comment]
Great, i'll propagate your fix to 🌐

**Comment by ofloveandhate** [comment]
done, fixed for all instructors.
