### ISSUE TITLE
Substitution training set, problem 3

### ISSUE THREAD

**Issue by weshuu** [ofloveandhate/calculus_1#58]
The part that asks for a fraction, say dx=5cos(x)/du, actually thinks multiplying is correct, as in dx=(5cos(x))du. The surrounding text asks for the fraction, which looks correct to me as well.

**Comment by ofloveandhate** [comment]
thanks for reporting, i see the bug on line 74.  i'll push a fix in a minute

**Comment by ofloveandhate** [comment]
fixed for all instructors and in repo

**Comment by ofloveandhate** [comment]
fixed in 94f525e
