### ISSUE TITLE
Comprehensive review, problem 13

### ISSUE THREAD

**Issue by weshuu** [ofloveandhate/calculus_1#62]
In the second of the three questions, it for some reason wants -(2^2) instead of (-2)^2. I'm not sure how this is happening based on the code.

**Comment by ofloveandhate** [comment]
i think you re-numbered your problems.  what's the path of the sourcecode for the problem?  (that's the problem's true name)

**Comment by weshuu** [comment]
setquiz_-_comprehensive_review_-_limits_derivs_applderivs_integrals_-_problems_same_for_all_students/productAndQuotientRule2.pg
