### ISSUE TITLE
Limits with formulas training, problem 11

### ISSUE THREAD

**Issue by weshuu** [ofloveandhate/calculus_1#7]
It says to "fill in the table" but there are no answer boxes in the table. I recommend we rephrase the instructions to "fill in the table on paper" (line 96).

**Comment by weshuu** [comment]
> It says to "fill in the table" but there are no answer boxes in the table. I recommend we rephrase the instructions to "fill in the table on paper" (line 96).

Testing quote reply

**Comment by ofloveandhate** [comment]
yeah, this is as written in the OPL, and the instructions should probably say "on paper".  do you think there's value in adding answer boxes?  seems like it might be busy work...  i'm just going to say "on paper".
