### ISSUE TITLE
Limits - rates of change - challenge, problem 4

### ISSUE THREAD

**Issue by weshuu** [ofloveandhate/calculus_1#8]
At the end, we do not specify to the student how many digits they must round to. I tested it, and it looks like 6 decimal places is enough but 5 is not. I suggest we edit the instructions to tell the students this. (If they lose these points due to insufficient decimal places, they have to do the whole test again to earn those points, correct?)

It pulls from "group limits and derivatives estimate instantaneous rate of change - no hints"; it's also number 4 of that.

My fix was: In place of the single $PAR on line 66, I insert the following:

$PAR

(When necessary, round all answers to 6 decimal places.)

$PAR

**Comment by ofloveandhate** [comment]
is this problem `setlimits_-_rates_of_change_-_concepts_and_story/Stewart5_2_1_7.pg`?

**Comment by ofloveandhate** [comment]
i think relaxing to like 3 decimal places would be good.

**Comment by ofloveandhate** [comment]
fixed in all instructors
